function [fitresult, gof] = createFit(contrasts, avg_loco)
%CREATEFIT(CONTRASTS,AVG_LOCO)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: contrasts
%      Y Output: avg_loco
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Mar-2023 13:20:29


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( contrasts, avg_loco );

% Set up fittype and options.
ft = fittype( 'atan(b*(a^2-x^2)/a/x)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.198819683720919 0.853905668387782];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'avg_loco vs. contrasts', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'contrasts', 'Interpreter', 'none' );
ylabel( 'avg_loco', 'Interpreter', 'none' );
grid on


